sudo: required
services:
  - docker

before_install:
  - docker build -t bugmakerwen/react-test -f ./client/Dockerfile.dev ./client

script:
  - - docker run -e CI=true bugmakerwen/react-test npm test

after_success:
  - docker build -t bugmakerwen/multi-client ./client
  - docker build -t bugmakerwen/multi-nginx ./nginx
  - docker build -t bugmakerwen/multi-server ./server
  - docker build -t bugmakerwen/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push bugmakerwen/multi-client
  - docker push bugmakerwen/multi-nginx
  - docker push bugmakerwen/multi-server
  - docker push bugmakerwen/multi-worker 

deploy:
  provider: elasticbeanstalk
  region: 'us-west-2'
  app: 'multi-docker'
  env: 'Multi-docker-env'
  bucket_name: 'elasticbeanstalk-us-west-2-764711331808'
  bucket_path: 'docker-multi'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY